//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearningSystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int id { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> stars { get; set; }
        public Nullable<bool> is_visible { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
