//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearningSystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Lesson
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> lesson_id { get; set; }
        public Nullable<bool> is_complete { get; set; }
        public Nullable<int> time { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual User User { get; set; }
    }
}
