//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearningSystem.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Course
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<bool> isowner { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
