// <auto-generated />
namespace eLearningSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ak : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ak));
        
        string IMigrationMetadata.Id
        {
            get { return "201911271748361_ak"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
