// <auto-generated />
namespace eLearningSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class chungchanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chungchanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201911250701394_chung-changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
